name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest #前ページのコンテナを使うという宣言
    steps:
      - uses: actions/checkout@v2    #コンテナのカレントディレクトリにリポジトリを配置
          
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/ros2robosys2023/    # リポジトリの下をros2_ws下にコピー
          cd /root/ros2_ws
          rosdep update
          rosdep install -r -y --from-paths --ignore-src ./
          colcon build
          bash -xv ./src/ros2robosys2023/test/test.bash /root
